export const ABOUT_TEXT = [
    "",
    "I’m a full stack developer based in Copenhagen, fascinated by large-scale, high-impact products and contributed to the development of features in industry-leading services.",
    "I’m increasingly focused on AI engineering, combining my web development experience with hands-on work in LLMs, embeddings, and intelligent applications.",
    "Currently channeling my energy into open source projects that aim to make a difference.",
    "",
    "Here are some of the technologies I work with regularly:",
    "",
    "- 🧠 LLMs",
    "- ✨ Generative AI",
    "- 🤖 OpenAI API",
    "- 🔎 Vector Databases",
    "- 🧩 Prompt Engineering",
    "- 🟦 TypeScript",
    "- 💛 JavaScript (ES6+)",
    "- ⚛️ React",
    "- ⬛ Next.js",
    "-  ⬢ Node.js",
    "- 🎨 Tailwind CSS",
    "- ⎇ Git",
    "",
    "Beyond the code, I find joy in creating art, tending to my garden, and experimenting in the kitchen.",
    "",
    "ABOUT_HIGHLIGHT:Feel free to explore more using the 'projects', 'experience', or 'contact' commands!",
    "",
  ];
