export const EXPERIENCE_TEXT = [
    "💼 Work Experience:",
    "",
    "Open Source Developer | Puter (April 2025)",
    "- Contributed to window layout bug in the json editor app.",
    "",
    "FullStack Developer | KMD (September 2021- December 2024)",
    "- Built a medication form using Formik + Yup for robust validation.",
    "- Contributed to migration ofAngularJS to React with TypeScript for critical systems.",
    "- Refactored legacy SASS, boosting Lighthouse score and load performance.",
    "",
    "Communication and External Relations | Platform Universal (May 2020- September 2020)",
    "- Built outreach strategies with universities, press, NGOs, and businesses.",
    "- Designed visual content and assisted in writing marketing materials.",
    "",
    "Search Engine Optimization | Fiverr (August 2016- February 2019)",
    "- Boosted local rankings via optimized metadata and content structure.",
    "- Applied mobile-first UX with click-to-call and responsive design.",
    "",
    "System Analyst | Tata Consultancy Services (June 2013- September 2015)",
    "- Led QA, SIT, and UAT; reduced bug resolution time by 25%.",
    "- Worked cross-functionally to document bugs and streamline testing.",
    "Mainframe Developer | Tata Consultancy Services (February 2012- May 2013)",
    "- Developed and maintained core business applications using COBOL.", 
    "- Utilized JCL to automate job execution and optimize processing efficiency.",
    "",
  ];