[build]
  command = "pnpm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://*.netlify.app/*"
  to = "https://niveditarani.dev/:splat"
  status = 301
  force = true  
